name: saludo

# 1. Evento que dispara el flujo
on:
  push:
    branches:
      - main 
      - develop

# 2. Definición de trabajos
jobs:
  saludar-job:
    runs-on: ubuntu-latest

    # 3. Los pasos van DENTRO del job (alineados con "runs-on")
    steps:
      - name: mostrar saludo
        run: echo "hola desde github actions"
        
      - name: mostrar perfil
        env:
          USUARIO_ACTUAL: ${{ github.actor }}
        run: |
          echo "1 autor: $USUARIO_ACTUAL"
          echo "2 evento: ${{ github.event_name }}"
          echo "3 repo: ${{ github.repository }}"
          echo "4 ref: ${{ github.ref_name }}"

    
